import 'multiboot_plan.dart';

/// Builds a GRUB 2 menu that chain-loads Windows Setup and loop-boots Linux ISOs.
String buildGrubConfig(MultiIsoPlan plan) {
  final buffer = StringBuffer()
    ..writeln(
      '# Generated by USB ISO Mount. Do not edit while writing the USB.',
    )
    ..writeln('set timeout=15')
    ..writeln('set default=0')
    ..writeln('insmod part_gpt')
    ..writeln('insmod fat')
    ..writeln('insmod exfat')
    ..writeln('insmod ntfs')
    ..writeln('insmod iso9660')
    ..writeln('insmod loopback')
    ..writeln('insmod linux')
    ..writeln('insmod chain')
    ..writeln();

  for (final item in plan.items) {
    if (item.role == MultiIsoRole.windows) {
      _writeWindowsEntry(buffer, item);
    } else {
      _writeLinuxEntry(buffer, item);
    }
  }

  buffer
    ..writeln('menuentry "Reboot" {')
    ..writeln('    reboot')
    ..writeln('}')
    ..writeln()
    ..writeln('menuentry "UEFI firmware settings" {')
    ..writeln('    fwsetup')
    ..writeln('}');
  return buffer.toString();
}

String grubTrampolineConfig() {
  return 'search --file --set=root /boot/grub/grub.cfg\n'
      'set prefix=(\$root)/boot/grub\n'
      'configfile /boot/grub/grub.cfg\n';
}

void _writeWindowsEntry(StringBuffer buffer, MultiIsoItem item) {
  final searchFiles = <String>{
    if (item.profile.bootWimPath != null) ...[
      '/sources/boot.wim',
      '/Sources/boot.wim',
    ],
    if (item.profile.installImagePath != null)
      '/sources/${_basename(item.profile.installImagePath!)}',
    '/sources/boot.wim',
    '/Sources/boot.wim',
    '/sources/install.wim',
    '/Sources/install.wim',
    '/sources/install.esd',
    '/Sources/install.esd',
  };
  final efiFiles = item.profile.hasArmEfi && !item.profile.hasX64Efi
      ? const [
          '/efi/boot/bootaa64.efi',
          '/EFI/BOOT/BOOTAA64.EFI',
          '/EFI/Boot/bootaa64.efi',
        ]
      : const [
          '/efi/boot/bootx64.efi',
          '/EFI/BOOT/BOOTX64.EFI',
          '/EFI/Boot/bootx64.efi',
        ];
  buffer
    ..writeln('menuentry "${_escape(item.menuTitle)}" {')
    ..writeln('    insmod part_gpt')
    ..writeln('    insmod exfat')
    ..writeln('    insmod ntfs')
    ..writeln('    insmod fat');
  var first = true;
  for (final file in searchFiles) {
    final cmd = 'search --file --no-floppy --set=root $file';
    buffer.writeln(first ? '    if $cmd; then' : '    elif $cmd; then');
    buffer.writeln('        true');
    first = false;
  }
  buffer.writeln('    fi');
  first = true;
  for (final efi in efiFiles) {
    buffer.writeln(
      first ? '    if [ -f $efi ]; then' : '    elif [ -f $efi ]; then',
    );
    buffer.writeln('        chainloader $efi');
    first = false;
  }
  buffer
    ..writeln('    else')
    ..writeln('        chainloader ${efiFiles.first}')
    ..writeln('    fi')
    ..writeln('}')
    ..writeln();
}

void _writeLinuxEntry(StringBuffer buffer, MultiIsoItem item) {
  final boot = item.linuxBoot;
  if (boot == null) {
    return;
  }
  final iso = item.isoPathOnUsb;
  final args = boot.kernelArguments(iso);
  buffer
    ..writeln('menuentry "${_escape(item.menuTitle)}" {')
    ..writeln('    set isofile="${_escape(iso)}"')
    ..writeln(r'    search --file --no-floppy --set=root $isofile')
    ..writeln(r'    loopback loop $isofile')
    ..writeln('    linux (loop)/${boot.kernelPath} $args')
    ..writeln('    initrd (loop)/${boot.initrdPath}')
    ..writeln('}')
    ..writeln();
}

String _escape(String value) {
  return value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
}

String _basename(String path) {
  final normalized = path.replaceAll(r'\', '/');
  final slash = normalized.lastIndexOf('/');
  return slash < 0 ? normalized : normalized.substring(slash + 1);
}
